export const situacaoFamiliar = [
    { "name": "situacaoFamiliar", "label": "Situação Familiar Instável", "type": "boolean" },
    { "name": "AceitacaoGravidez", "label": "Aceitação da Gravidez", "type": "boolean" },
    { "name": "sabeLer", "label": "Analfabeto", "type": "boolean" },
    { "name": "fumante", "label": "Fumante", "type": "boolean" },
    { "name": "dependenteDrogas", "label": "Dependente de Drogas", "type": "boolean" },
    { "name": "expostaRiscoOcupacional", "label": "Exposta a Risco Ocupacional", "type": "boolean" },
    { "name": "expostaCondAmbientais", "label": "Exposta a Condições Ambientais", "type": "boolean" }
]

export const historicoObst = [
    { "name": "histRnCrescimento", "label": "História de recém-nascido com crescimento restrito ou Malformação Fetal", "type": "boolean" },
    { "name": "intervaloInterpartal", "label": "Intervalo interpartal menor que dois anos ou maior que cinco anos", "type": "boolean" },
    { "name": "eclampsia", "label": "Eclampsia", "type": "boolean" },
    { "name": "preEclampsia", "label": "Pré-eclampsia", "type": "boolean" },
    { "name": "placentaPrevia", "label": "Placenta Prévia", "type": "boolean" },
    { "name": "insuficienciaIstmoCervical", "label": "Insuficiência de Istmo Cervical", "type": "boolean" },
    { "name": "cesarea12", "label": "1-2 cesáreas anteriores", "type": "boolean" },
    { "name": "cesarea3Mais", "label": "3 ou mais cesáreas anteriores", "type": "boolean" },
    { "name": "ultimoPartoMenos12", "label": "Último Parto Menos de 12 meses", "type": "boolean" },
    { "name": "diabetesGestacional", "label": "Diabetes Gestacional", "type": "boolean" },
    { "name": "nuliparidadeMultiparidade", "label": "Nuliparidade e grande multiparidade", "type": "boolean" },
    { "name": "placentaPreviaAtual", "label": "Placenta Prévia Atual", "type": "boolean" },
    { "name": "acrestismoPlacentario", "label": "Acretismo Placentário", "type": "boolean" },
    { "name": "aloimunizacao", "label": "Aloimunização / Doença Hemolítica", "type": "boolean" },
    { "name": "esterilidadeTratada", "label": "Esterilidade Tratada", "type": "boolean" },
    { "name": "malformacoesCongenitas", "label": "Malformações Congênitas", "type": "boolean" },
    { "name": "ciur", "label": "CIUR – Crescimento Intra-uterino Restrito", "type": "boolean" },
    { "name": "polidramnioOligodramnio", "label": "Polidrâmnio / Oligodrâmnio", "type": "boolean" },
    { "name": "citologiaCervicalAnormal", "label": "Citologia Cervical Anormal ( NIC I, II, III)", "type": "boolean" },
    { "name": "diabetesGestacionalTrat", "label": "Diabetes Gestacional em tratamento bem sucedido com dieta", "type": "boolean" },
    { "name": "diabetesGestacionalInsul", "label": "Diabetes Gestacional Insulino Dependente", "type": "boolean" },
    { "name": "gestacaoDicorionica", "label": "Gestação Gemelar Dicoriônica", "type": "boolean" },
    { "name": "gestacaoMonocorionica", "label": "Gestação Gemelar Monocoriônico ou Mais de Dois Fetos", "type": "boolean" },
    { "name": "insufIstmoCervicalAtual", "label": "Insuficiência Istmo-cervical", "type": "boolean" },
    { "name": "trabalhoPartoPrematuro", "label": "Trabalho de parto prematuro ou gravidez prolongada", "type": "boolean" }
]

export const condicoesMedicas = [
    { "name": "tromboembolismoGestacao", "label": "Tromboembolismo na Gestação", "type": "boolean" },
    { "name": "preEclampsiaAtual", "label": "Pré-eclâmpsia qualquer tipo", "type": "boolean" },
    { "name": "aneurisma", "label": "Aneurisma", "type": "boolean" },
    { "name": "aterosclerose", "label": "Aterosclerose", "type": "boolean" },
    { "name": "alteracoesOsteo", "label": "Alterações osteo-articulares de interesse obstétrico", "type": "boolean" },
    { "name": "varizesAcentuadas", "label": "Varizes Acentuadas", "type": "boolean" },
    { "name": "cardiopatias", "label": "Cardiopatias", "type": "boolean" },
    { "name": "cirurgiaUterina", "label": "Cirurgia Uterina Prévia", "type": "boolean" },
    { "name": "diabetesInsulino", "label": "Diabetes Insulino Dependente", "type": "boolean" },
    { "name": "diabetesMellitus", "label": "Diabetes Mellitus tratada com HO", "type": "boolean" },
    { "name": "doencasAutoImunesFora", "label": "Doenças auto-imunes , LES e outras colagenoses fora de atividade", "type": "boolean" },
    { "name": "doencasAutoImunesTrat", "label": "Doenças auto-imunes, LES e outras colagenoses necessitando de tratamento e acompanhamento conjunto", "type": "boolean" },
    { "name": "doencasIntestinais", "label": "Doenças inflamatórias intestinais crônicas", "type": "boolean" },
    { "name": "tireoidopatias", "label": "Tireoidopatias necessitando de tratamento e acompanhamentoconjunto", "type": "boolean" },
    { "name": "endometriose", "label": "Endometriose", "type": "boolean" },
    { "name": "epilepsiaNeurologica", "label": "Epilepsia ou Doença Neurológica Crônica", "type": "boolean" },
    { "name": "ginecopatias", "label": "Ginecopatias (malformação uterina, miomatose, tumores anexiais e outros)", "type": "boolean" },
    { "name": "anomaliaOrganosReprodutivos", "label": "Existem anormalidades estruturais nos órgãos reprodutivos?", "type": "boolean" },
    { "name": "hepatopatiasTratamento", "label": "Hepatopatias necessitando de tratamento e acompanhamento conjunto", "type": "boolean" },
    { "name": "hipertensaoArterial", "label": "Hipertensão Arterial Crônica", "type": "boolean" },
    { "name": "nefropatias", "label": "Nefropatias", "type": "boolean" },
    { "name": "ituRepeticao", "label": "ITU repetição ou Pileonefrite na Gestação", "type": "boolean" },
    { "name": "pneumopatias", "label": "Pneumopatias com necessidade de tratamento", "type": "boolean" },
    { "name": "traumaObstetrico", "label": "Trauma com repercussões que possam interferir na vida obstrétrica", "type": "boolean" },
    { "name": "tromboembolismo", "label": "Tromboembolismo", "type": "boolean" },
    { "name": "trombofiliaAdquirida", "label": "Trombofilia adquirida (SAAF)", "type": "boolean" },
    { "name": "trombofiliaHereditaria", "label": "Trombofilia hereditária", "type": "boolean" },
    { "name": "doencasInfecciosasBucais", "label": "Doenças infecciosas bucais", "type": "boolean" },
    { "name": "hepatites", "label": "Hepatites", "type": "boolean" },
    { "name": "toxoplasmose", "label": "Toxoplasmose", "type": "boolean" },
    { "name": "sifilis", "label": "Sifilis", "type": "boolean" },
    { "name": "hiv", "label": "HIV", "type": "boolean" },
    { "name": "outrosDsts", "label": "Outros DSTs", "type": "boolean" },
    { "name": "doencasPsiquiatricas", "label": "Doenças Psiquiatrica em uso de mediação e necessidade de acompanhamento psiquiátrico em conjunto", "type": "boolean" },
    { "name": "neoplasias", "label": "Neoplasias", "type": "boolean" },
    { "name": "doencasInfectoGestacao", "label": "Doenças infectocontagiosas vividas durante a presente gestação (ITU, doenças do trato, respiratório, tuberculose, rubéola, gengivites e periodontites, toxoplasmose etc.)", "type": "boolean" },
    { "name": "sepse", "label": "Sepse ", "type": "boolean" },
    { "name": "doencasClinicasGestacao", "label": "Doenças clínicas diagnosticadas pela primeira vez nessa gestação (cardiopatias, endocrinopatias)", "type": "boolean" }
]

export const initialCalculadoraValue = {
    nomeCompleto: "",
    cpf: "",
    dataNascimento: "",
    telefone: "",
    email: "",
    idPaciente: "",
    dtCalculo: "",
    idUsuario: "",
    idEmpresa: "",
    idadeGestante: "0",
    alturaGestante: "0",
    pesoKg: "0",
    imc: "0",
    hrCalculo: "",
    IdadeGestacionalSemanas: "0",
    IdadeGestacionalDias: "0",
    qtAborto: "0",
    qtNatimorto: "0",
    qtPartoPrematuro: "0",
    ...situacaoFamiliar.reduce((acc, curr) => ({ ...acc, [curr.name]: "N" }), {}),
    ...historicoObst.reduce((acc, curr) => ({ ...acc, [curr.name]: "N" }), {}),
    ...condicoesMedicas.reduce((acc, curr) => ({ ...acc, [curr.name]: "N" }), {})
}